apiVersion: v1
kind: Service
metadata:
  name: {{ include "adcf.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "adcf.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    uars.platform/component: "adcf"
    uars.platform/service-type: "core"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: metrics
  selector:
    {{- include "adcf.selectorLabels" . | nindent 4 }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
---
# Headless service for StatefulSet-like behavior
apiVersion: v1
kind: Service
metadata:
  name: {{ include "adcf.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "adcf.labels" . | nindent 4 }}
    service-type: headless
  annotations:
    uars.platform/component: "adcf"
    uars.platform/service-type: "headless"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: metrics
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: p2p
  selector:
    {{- include "adcf.selectorLabels" . | nindent 4 }}
  publishNotReadyAddresses: true
