global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # UARS-7 Services
  - job_name: 'cads'
    static_configs:
      - targets: ['cads:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'm-ses'
    static_configs:
      - targets: ['m-ses:8081']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'shel'
    static_configs:
      - targets: ['shel:8082']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'ilecg'
    static_configs:
      - targets: ['ilecg:8083']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'qvdm'
    static_configs:
      - targets: ['qvdm:8084']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'trdn'
    static_configs:
      - targets: ['trdn:8085']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'adcf'
    static_configs:
      - targets: ['adcf:8086']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Infrastructure
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Kubernetes (when deployed)
  - job_name: 'kubernetes-apiservers'
    kubernetes_sd_configs:
    - role: endpoints
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
    - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
      action: keep
      regex: default;kubernetes;https

  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
    - role: node
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)

  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
      action: keep
      regex: true
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
      action: replace
      target_label: __metrics_path__
      regex: (.+)
    - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
      action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:$2
      target_label: __address__
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    - source_labels: [__meta_kubernetes_namespace]
      action: replace
      target_label: kubernetes_namespace
    - source_labels: [__meta_kubernetes_pod_name]
      action: replace
      target_label: kubernetes_pod_name
